; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\lpc1768_timer.o --depend=.\objects\lpc1768_timer.d --cpu=Cortex-M3 --apcs=interwork -O0 --diag_suppress=9931 -I.\Drivers -I.\RTE\Device\LPC1768 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\CMSIS\Core\Include -IC:\Keil_v5\ARM\PACK\Keil\LPC1700_DFP\2.5.0\Device\Include -D__UVISION_VERSION=524 -D_RTE_ -DLPC175x_6x --omf_browse=.\objects\lpc1768_timer.crf Drivers\lpc1768_timer.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.Timer_configure||, CODE, READONLY, ALIGN=1

Timer_configure PROC
        LDR      r2,[r1,#8]
        STR      r2,[r0,#0x14]
        BX       lr
        ENDP


        AREA ||i.Timer_init||, CODE, READONLY, ALIGN=1

Timer_init PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        MOV      r1,r4
        LDR      r0,[r4,#0]
        BL       Timer_configure
        LDR      r0,[r4,#0]
        BL       getPrescalarValue
        LDR      r1,[r4,#0]
        STR      r0,[r1,#0xc]
        LDRD     r1,r0,[r4,#0]
        STR      r0,[r1,#0x18]
        POP      {r4,pc}
        ENDP


        AREA ||i.Timer_setTime||, CODE, READONLY, ALIGN=1

Timer_setTime PROC
        STR      r1,[r0,#0x18]
        BX       lr
        ENDP


        AREA ||i.Timer_start||, CODE, READONLY, ALIGN=1

Timer_start PROC
        MOVS     r1,#0
        STR      r1,[r0,#8]
        LDR      r1,[r0,#4]
        ORR      r1,r1,#1
        STR      r1,[r0,#4]
        BX       lr
        ENDP


        AREA ||i.Timer_stop||, CODE, READONLY, ALIGN=1

Timer_stop PROC
        MOVS     r1,#0
        STR      r1,[r0,#4]
        BX       lr
        ENDP


        AREA ||i.getPrescalarValue||, CODE, READONLY, ALIGN=2

getPrescalarValue PROC
        PUSH     {r4,lr}
        MOV      r3,r0
        CMP      r3,#0x40004000
        BNE      |L6.20|
        LDR      r4,|L6.124|
        LDR      r4,[r4,#0]
        UBFX     r1,r4,#2,#2
        B        |L6.64|
|L6.20|
        LDR      r4,|L6.128|
        CMP      r3,r4
        BNE      |L6.36|
        LDR      r4,|L6.124|
        LDR      r4,[r4,#0]
        UBFX     r1,r4,#4,#2
        B        |L6.64|
|L6.36|
        LDR      r4,|L6.132|
        CMP      r3,r4
        BNE      |L6.54|
        LDR      r4,|L6.124|
        ADDS     r4,r4,#4
        LDR      r4,[r4,#0]
        UBFX     r1,r4,#12,#2
        B        |L6.64|
|L6.54|
        LDR      r4,|L6.124|
        ADDS     r4,r4,#4
        LDR      r4,[r4,#0]
        UBFX     r1,r4,#14,#2
|L6.64|
        CBZ      r1,|L6.80|
        CMP      r1,#1
        BEQ      |L6.88|
        CMP      r1,#2
        BEQ      |L6.94|
        CMP      r1,#3
        BNE      |L6.110|
        B        |L6.102|
|L6.80|
        LDR      r4,|L6.136|
        LDR      r4,[r4,#0]  ; SystemCoreClock
        LSRS     r2,r4,#2
        B        |L6.110|
|L6.88|
        LDR      r4,|L6.136|
        LDR      r2,[r4,#0]  ; SystemCoreClock
        B        |L6.110|
|L6.94|
        LDR      r4,|L6.136|
        LDR      r4,[r4,#0]  ; SystemCoreClock
        LSRS     r2,r4,#1
        B        |L6.110|
|L6.102|
        LDR      r4,|L6.136|
        LDR      r4,[r4,#0]  ; SystemCoreClock
        LSRS     r2,r4,#3
        NOP      
|L6.110|
        NOP      
        MOV      r4,#0x3e8
        UDIV     r4,r2,r4
        SUBS     r0,r4,#1
        POP      {r4,pc}
        ENDP

|L6.124|
        DCD      0x400fc1a8
|L6.128|
        DCD      0x40008000
|L6.132|
        DCD      0x40090000
|L6.136|
        DCD      SystemCoreClock

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "Drivers\\lpc1768_timer.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___15_lpc1768_timer_c_2a4c602b____REV16|
#line 463 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.4.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___15_lpc1768_timer_c_2a4c602b____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___15_lpc1768_timer_c_2a4c602b____REVSH|
#line 478
|__asm___15_lpc1768_timer_c_2a4c602b____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___15_lpc1768_timer_c_2a4c602b____RRX|
#line 665
|__asm___15_lpc1768_timer_c_2a4c602b____RRX| PROC
#line 666

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT Timer_init [CODE]
        EXPORT Timer_setTime [CODE]
        EXPORT Timer_start [CODE]
        EXPORT Timer_stop [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT SystemCoreClock [DATA]

        KEEP Timer_configure
        KEEP getPrescalarValue

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
