; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\lpc1768_led.o --depend=.\objects\lpc1768_led.d --cpu=Cortex-M3 --apcs=interwork -O0 --diag_suppress=9931 -I.\Drivers -I.\RTE\Device\LPC1768 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\CMSIS\Core\Include -IC:\Keil_v5\ARM\PACK\Keil\LPC1700_DFP\2.5.0\Device\Include -D__UVISION_VERSION=524 -D_RTE_ -DLPC175x_6x --omf_browse=.\objects\lpc1768_led.crf Drivers\lpc1768_led.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.LED_init||, CODE, READONLY, ALIGN=1

LED_init PROC
        PUSH     {r4,lr}
        MOVS     r2,#1
        MOVS     r1,#0x12
        MOV      r0,r2
        BL       GPIO_PinDirection
        MOVS     r2,#1
        MOVS     r1,#0x14
        MOV      r0,r2
        BL       GPIO_PinDirection
        MOVS     r2,#1
        MOVS     r1,#0x15
        MOV      r0,r2
        BL       GPIO_PinDirection
        MOVS     r2,#1
        MOVS     r1,#0x17
        MOV      r0,r2
        BL       GPIO_PinDirection
        MOVS     r2,#0
        MOVS     r1,#0x12
        MOVS     r0,#1
        BL       GPIO_PinFunction
        MOVS     r2,#0
        MOVS     r1,#0x14
        MOVS     r0,#1
        BL       GPIO_PinFunction
        MOVS     r2,#0
        MOVS     r1,#0x15
        MOVS     r0,#1
        BL       GPIO_PinFunction
        MOVS     r2,#0
        MOVS     r1,#0x17
        MOVS     r0,#1
        BL       GPIO_PinFunction
        POP      {r4,pc}
        ENDP


        AREA ||i.LED_off||, CODE, READONLY, ALIGN=1

LED_off PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        CMP      r4,#4
        BGE      |L2.64|
        CBNZ     r4,|L2.22|
        MOVS     r2,#0
        MOVS     r1,#0x12
        MOVS     r0,#1
        BL       GPIO_PinWrite
        B        |L2.64|
|L2.22|
        CMP      r4,#1
        BNE      |L2.38|
        MOVS     r2,#0
        MOVS     r1,#0x14
        MOVS     r0,#1
        BL       GPIO_PinWrite
        B        |L2.64|
|L2.38|
        CMP      r4,#2
        BNE      |L2.54|
        MOVS     r2,#0
        MOVS     r1,#0x15
        MOVS     r0,#1
        BL       GPIO_PinWrite
        B        |L2.64|
|L2.54|
        MOVS     r2,#0
        MOVS     r1,#0x17
        MOVS     r0,#1
        BL       GPIO_PinWrite
|L2.64|
        POP      {r4,pc}
        ENDP


        AREA ||i.LED_on||, CODE, READONLY, ALIGN=1

LED_on PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        CMP      r4,#4
        BGE      |L3.64|
        CBNZ     r4,|L3.22|
        MOVS     r2,#1
        MOVS     r1,#0x12
        MOV      r0,r2
        BL       GPIO_PinWrite
        B        |L3.64|
|L3.22|
        CMP      r4,#1
        BNE      |L3.38|
        MOVS     r2,#1
        MOVS     r1,#0x14
        MOV      r0,r2
        BL       GPIO_PinWrite
        B        |L3.64|
|L3.38|
        CMP      r4,#2
        BNE      |L3.54|
        MOVS     r2,#1
        MOVS     r1,#0x15
        MOV      r0,r2
        BL       GPIO_PinWrite
        B        |L3.64|
|L3.54|
        MOVS     r2,#1
        MOVS     r1,#0x17
        MOV      r0,r2
        BL       GPIO_PinWrite
|L3.64|
        POP      {r4,pc}
        ENDP


        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "Drivers\\lpc1768_led.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___13_lpc1768_led_c_LED_init____REV16|
#line 463 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.4.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___13_lpc1768_led_c_LED_init____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___13_lpc1768_led_c_LED_init____REVSH|
#line 478
|__asm___13_lpc1768_led_c_LED_init____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___13_lpc1768_led_c_LED_init____RRX|
#line 665
|__asm___13_lpc1768_led_c_LED_init____RRX| PROC
#line 666

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT LED_init [CODE]
        EXPORT LED_off [CODE]
        EXPORT LED_on [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT GPIO_PinDirection [CODE]
        IMPORT GPIO_PinFunction [CODE]
        IMPORT GPIO_PinWrite [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
