; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\lpc1768_gpio.o --depend=.\objects\lpc1768_gpio.d --cpu=Cortex-M3 --apcs=interwork -O0 --diag_suppress=9931 -I.\Drivers -I.\RTE\Device\LPC1768 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\CMSIS\Core\Include -IC:\Keil_v5\ARM\PACK\Keil\LPC1700_DFP\2.5.0\Device\Include -D__UVISION_VERSION=524 -D_RTE_ -DLPC175x_6x --omf_browse=.\objects\lpc1768_gpio.crf Drivers\lpc1768_gpio.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.GPIO_PinDirection||, CODE, READONLY, ALIGN=2

GPIO_PinDirection PROC
        PUSH     {r4,lr}
        CMP      r0,#5
        BGE      |L1.182|
        CMP      r1,#0x20
        BGE      |L1.182|
        CMP      r0,#5
        BCS      |L1.180|
        TBB      [pc,r0]
        DCB      0x03,0x12
        DCB      0x21,0x30,0x3e,0x00
        LDR      r3,|L1.184|
        LDR      r3,[r3,#0]
        MOVS     r4,#1
        LSLS     r4,r4,r1
        BICS     r3,r3,r4
        LDR      r4,|L1.184|
        STR      r3,[r4,#0]
        MOV      r3,r4
        LDR      r3,[r3,#0]
        LSL      r4,r2,r1
        ORRS     r3,r3,r4
        LDR      r4,|L1.184|
        STR      r3,[r4,#0]
        B        |L1.180|
        LDR      r3,|L1.184|
        LDR      r3,[r3,#0x20]
        MOVS     r4,#1
        LSLS     r4,r4,r1
        BICS     r3,r3,r4
        LDR      r4,|L1.184|
        STR      r3,[r4,#0x20]
        MOV      r3,r4
        LDR      r3,[r3,#0x20]
        LSL      r4,r2,r1
        ORRS     r3,r3,r4
        LDR      r4,|L1.184|
        STR      r3,[r4,#0x20]
        B        |L1.180|
        LDR      r3,|L1.184|
        LDR      r3,[r3,#0x40]
        MOVS     r4,#1
        LSLS     r4,r4,r1
        BICS     r3,r3,r4
        LDR      r4,|L1.184|
        STR      r3,[r4,#0x40]
        MOV      r3,r4
        LDR      r3,[r3,#0x40]
        LSL      r4,r2,r1
        ORRS     r3,r3,r4
        LDR      r4,|L1.184|
        STR      r3,[r4,#0x40]
        B        |L1.180|
        LDR      r3,|L1.184|
        LDR      r4,[r3,#0x60]
        MOVS     r3,#1
        LSLS     r3,r3,r1
        BICS     r4,r4,r3
        LDR      r3,|L1.184|
        STR      r4,[r3,#0x60]
        LDR      r3,[r3,#0x60]
        LSL      r4,r2,r1
        ORRS     r3,r3,r4
        LDR      r4,|L1.184|
        STR      r3,[r4,#0x60]
        B        |L1.180|
        LDR      r3,|L1.184|
        ADDS     r3,r3,#0x80
        LDR      r4,[r3,#0]
        MOVS     r3,#1
        LSLS     r3,r3,r1
        BICS     r4,r4,r3
        LDR      r3,|L1.184|
        STR      r4,[r3,#0x80]
        LDR      r3,|L1.184|
        ADDS     r3,r3,#0x80
        LDR      r3,[r3,#0]
        LSL      r4,r2,r1
        ORRS     r3,r3,r4
        LDR      r4,|L1.184|
        STR      r3,[r4,#0x80]
        NOP      
|L1.180|
        NOP      
|L1.182|
        POP      {r4,pc}
        ENDP

|L1.184|
        DCD      0x2009c000

        AREA ||i.GPIO_PinFunction||, CODE, READONLY, ALIGN=2

GPIO_PinFunction PROC
        PUSH     {r4-r7,lr}
        MOV      r3,r0
        MOV      r4,r1
        MOV      r5,r2
        MOV      r2,r4
        CMP      r3,#5
        BGE      |L2.106|
        CMP      r4,#0x20
        BGE      |L2.106|
        CMP      r5,#3
        BHI      |L2.106|
        CMP      r3,#5
        BCS      |L2.56|
        TBB      [pc,r3]
        DCB      0x03,0x05
        DCB      0x07,0x09,0x0b,0x00
        MOVS     r0,#0
        B        |L2.56|
        MOVS     r0,#2
        B        |L2.56|
        MOVS     r0,#4
        B        |L2.56|
        MOVS     r0,#6
        B        |L2.56|
        MOVS     r0,#8
        NOP      
|L2.56|
        NOP      
        CMP      r4,#0xf
        BLE      |L2.72|
        ADDS     r6,r0,#1
        UXTB     r0,r6
        SUB      r6,r2,#0x10
        UXTH     r2,r6
|L2.72|
        MOV      r6,#0xffff
        AND      r2,r6,r2,LSL #1
        LDR      r6,|L2.108|
        ADD      r1,r6,r0,LSL #2
        MOVS     r7,#3
        LSLS     r7,r7,r2
        LDR      r6,[r1,#0]
        BICS     r6,r6,r7
        STR      r6,[r1,#0]
        LSL      r7,r5,r2
        LDR      r6,[r1,#0]
        ORRS     r6,r6,r7
        STR      r6,[r1,#0]
|L2.106|
        POP      {r4-r7,pc}
        ENDP

|L2.108|
        DCD      0x4002c000

        AREA ||i.GPIO_PinInit||, CODE, READONLY, ALIGN=1

GPIO_PinInit PROC
        PUSH     {r0-r3}
        PUSH     {lr}
        LDRD     r3,r2,[sp,#8]
        UXTH     r1,r3
        LDR      r3,[sp,#4]
        UXTB     r0,r3
        BL       GPIO_PinFunction
        LDR      r3,[sp,#0x14]
        UXTB     r2,r3
        LDR      r3,[sp,#8]
        UXTH     r1,r3
        LDR      r3,[sp,#4]
        UXTB     r0,r3
        BL       GPIO_PinDirection
        LDR      pc,[sp],#0x14
        ENDP


        AREA ||i.GPIO_PinRead||, CODE, READONLY, ALIGN=2

GPIO_PinRead PROC
        PUSH     {r4,lr}
        MOV      r2,r0
        MOVS     r0,#0
        CMP      r2,#5
        BGE      |L4.142|
        CMP      r1,#0x20
        BGE      |L4.142|
        CMP      r2,#5
        BCS      |L4.140|
        TBB      [pc,r2]
        DCB      0x03,0x0e
        DCB      0x19,0x24,0x2f,0x00
        LDR      r3,|L4.144|
        LDR      r3,[r3,#0x14]
        MOVS     r4,#1
        LSLS     r4,r4,r1
        ANDS     r3,r3,r4
        CBZ      r3,|L4.44|
        MOVS     r3,#1
        B        |L4.46|
|L4.44|
        MOVS     r3,#0
|L4.46|
        MOV      r0,r3
        B        |L4.140|
        LDR      r3,|L4.144|
        LDR      r3,[r3,#0x34]
        MOVS     r4,#1
        LSLS     r4,r4,r1
        ANDS     r3,r3,r4
        CBZ      r3,|L4.66|
        MOVS     r3,#1
        B        |L4.68|
|L4.66|
        MOVS     r3,#0
|L4.68|
        MOV      r0,r3
        B        |L4.140|
        LDR      r3,|L4.144|
        LDR      r3,[r3,#0x54]
        MOVS     r4,#1
        LSLS     r4,r4,r1
        ANDS     r3,r3,r4
        CBZ      r3,|L4.88|
        MOVS     r3,#1
        B        |L4.90|
|L4.88|
        MOVS     r3,#0
|L4.90|
        MOV      r0,r3
        B        |L4.140|
        LDR      r3,|L4.144|
        LDR      r4,[r3,#0x74]
        MOVS     r3,#1
        LSLS     r3,r3,r1
        ANDS     r4,r4,r3
        CBZ      r4,|L4.110|
        MOVS     r3,#1
        B        |L4.112|
|L4.110|
        MOVS     r3,#0
|L4.112|
        MOV      r0,r3
        B        |L4.140|
        LDR      r3,|L4.144|
        ADDS     r3,r3,#0x94
        LDR      r4,[r3,#0]
        MOVS     r3,#1
        LSLS     r3,r3,r1
        ANDS     r4,r4,r3
        CBZ      r4,|L4.134|
        MOVS     r3,#1
        B        |L4.136|
|L4.134|
        MOVS     r3,#0
|L4.136|
        MOV      r0,r3
        NOP      
|L4.140|
        NOP      
|L4.142|
        POP      {r4,pc}
        ENDP

|L4.144|
        DCD      0x2009c000

        AREA ||i.GPIO_PinWrite||, CODE, READONLY, ALIGN=2

GPIO_PinWrite PROC
        PUSH     {r4,r5,lr}
        MOV      r3,r0
        CMP      r3,#5
        BGE      |L5.44|
        CMP      r1,#0x20
        BGE      |L5.44|
        LDR      r4,|L5.48|
        ADD      r0,r4,r3,LSL #5
        CMP      r2,#1
        BNE      |L5.34|
        LDR      r4,[r0,#0x18]
        MOVS     r5,#1
        LSLS     r5,r5,r1
        ORRS     r4,r4,r5
        STR      r4,[r0,#0x18]
        B        |L5.44|
|L5.34|
        LDR      r4,[r0,#0x1c]
        MOVS     r5,#1
        LSLS     r5,r5,r1
        ORRS     r4,r4,r5
        STR      r4,[r0,#0x1c]
|L5.44|
        POP      {r4,r5,pc}
        ENDP

        DCW      0x0000
|L5.48|
        DCD      0x2009c000

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "Drivers\\lpc1768_gpio.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___14_lpc1768_gpio_c_1d4f2b10____REV16|
#line 463 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.4.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___14_lpc1768_gpio_c_1d4f2b10____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___14_lpc1768_gpio_c_1d4f2b10____REVSH|
#line 478
|__asm___14_lpc1768_gpio_c_1d4f2b10____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___14_lpc1768_gpio_c_1d4f2b10____RRX|
#line 665
|__asm___14_lpc1768_gpio_c_1d4f2b10____RRX| PROC
#line 666

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT GPIO_PinDirection [CODE]
        EXPORT GPIO_PinFunction [CODE]
        EXPORT GPIO_PinInit [CODE]
        EXPORT GPIO_PinRead [CODE]
        EXPORT GPIO_PinWrite [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
