; generated by Component: ARM Compiler 5.06 update 5 (build 528) Tool: ArmCC [4d3621]
; commandline ArmCC [--c99 --split_sections --debug -c --asm -o.\objects\system_lpc17xx.o --depend=.\objects\system_lpc17xx.d --cpu=Cortex-M3 --apcs=interwork -O0 --diag_suppress=9931 -I.\Drivers -I.\RTE\Device\LPC1768 -I.\RTE\_Target_1 -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.4.0\CMSIS\Core\Include -IC:\Keil_v5\ARM\PACK\Keil\LPC1700_DFP\2.5.0\Device\Include -D__UVISION_VERSION=524 -D_RTE_ -DLPC175x_6x --omf_browse=.\objects\system_lpc17xx.crf RTE\Device\LPC1768\system_LPC17xx.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.SystemCoreClockUpdate||, CODE, READONLY, ALIGN=2

SystemCoreClockUpdate PROC
        PUSH     {r4-r10,lr}
        LDR      r0,|L1.408|
        LDR      r0,[r0,#0]
        UBFX     r0,r0,#24,#2
        CMP      r0,#3
        BNE      |L1.268|
        LDR      r0,|L1.408|
        ADDS     r0,r0,#0x84
        LDR      r0,[r0,#0]
        AND      r0,r0,#3
        CBZ      r0,|L1.42|
        CMP      r0,#1
        BEQ      |L1.130|
        CMP      r0,#2
        BEQ      |L1.216|
        CMP      r0,#3
        BNE      |L1.128|
        B        |L1.44|
|L1.42|
        NOP      
|L1.44|
        LDR      r0,|L1.408|
        LDR      r0,[r0,#0]
        UBFX     r0,r0,#16,#8
        ADDS     r4,r0,#1
        MOVS     r1,#2
        LDR      r0,|L1.408|
        SUBS     r0,r0,#0x88
        LDR      r0,[r0,#0x88]
        UBFX     r0,r0,#0,#15
        ADDS     r0,r0,#1
        UMULL    r0,r1,r1,r0
        LDR      r3,|L1.412|
        MOV      r12,#0
        UMULL    r7,r9,r0,r3
        MLA      r1,r1,r3,r9
        MLA      r1,r0,r12,r1
        MOV      r2,r4
        MOV      r3,r12
        MOV      r0,r7
        BL       __aeabi_uldivmod
        MOV      r5,r0
        LDR      r0,|L1.408|
        ADDS     r0,r0,#0x7c
        LDR      r0,[r0,#0]
        UXTB     r0,r0
        ADDS     r4,r0,#1
        MOV      r2,r4
        MOVS     r3,#0
        MOV      r0,r5
        BL       __aeabi_uldivmod
        LDR      r1,|L1.416|
        STR      r0,[r1,#0]  ; SystemCoreClock
|L1.128|
        B        |L1.304|
|L1.130|
        LDR      r0,|L1.408|
        LDR      r0,[r0,#0]
        UBFX     r0,r0,#16,#8
        ADDS     r4,r0,#1
        MOVS     r1,#2
        LDR      r0,|L1.408|
        SUBS     r0,r0,#0x88
        LDR      r0,[r0,#0x88]
        UBFX     r0,r0,#0,#15
        ADDS     r0,r0,#1
        UMULL    r1,r0,r1,r0
        LDR      r2,|L1.420|
        MOV      r12,#0
        UMULL    r7,r9,r1,r2
        MLA      r0,r0,r2,r9
        MLA      r1,r1,r12,r0
        MOV      r2,r4
        MOV      r3,r12
        MOV      r0,r7
        BL       __aeabi_uldivmod
        MOV      r5,r0
        LDR      r0,|L1.408|
        ADDS     r0,r0,#0x7c
        LDR      r0,[r0,#0]
        UXTB     r0,r0
        ADDS     r4,r0,#1
        MOV      r2,r4
        MOVS     r3,#0
        MOV      r0,r5
        BL       __aeabi_uldivmod
        LDR      r1,|L1.416|
        STR      r0,[r1,#0]  ; SystemCoreClock
        B        |L1.304|
|L1.216|
        LDR      r0,|L1.408|
        LDR      r0,[r0,#0]
        UBFX     r0,r0,#16,#8
        ADDS     r4,r0,#1
        MOVS     r1,#2
        LDR      r0,|L1.408|
        SUBS     r0,r0,#0x88
        LDR      r0,[r0,#0x88]
        UBFX     r0,r0,#0,#15
        ADDS     r0,r0,#1
        UMULL    r1,r2,r1,r0
        MOV      r0,#0x8000
        MOVS     r3,#0
        UMULL    r7,r9,r1,r0
        MLA      r0,r2,r0,r9
        MLA      r1,r1,r3,r0
        MOV      r2,r4
        B        |L1.270|
|L1.268|
        B        |L1.306|
|L1.270|
        MOV      r0,r7
        BL       __aeabi_uldivmod
        MOV      r5,r0
        LDR      r0,|L1.408|
        ADDS     r0,r0,#0x7c
        LDR      r0,[r0,#0]
        UXTB     r0,r0
        ADDS     r4,r0,#1
        MOV      r2,r4
        MOVS     r3,#0
        MOV      r0,r5
        BL       __aeabi_uldivmod
        LDR      r1,|L1.416|
        STR      r0,[r1,#0]  ; SystemCoreClock
        NOP      
|L1.304|
        B        |L1.404|
|L1.306|
        LDR      r0,|L1.408|
        ADDS     r0,r0,#0x84
        LDR      r0,[r0,#0]
        AND      r0,r0,#3
        CBZ      r0,|L1.332|
        CMP      r0,#1
        BEQ      |L1.356|
        CMP      r0,#2
        BEQ      |L1.378|
        CMP      r0,#3
        BNE      |L1.402|
        B        |L1.334|
|L1.332|
        NOP      
|L1.334|
        LDR      r0,|L1.408|
        ADDS     r0,r0,#0x7c
        LDR      r0,[r0,#0]
        UXTB     r0,r0
        ADDS     r0,r0,#1
        LDR      r1,|L1.412|
        UDIV     r0,r1,r0
        LDR      r1,|L1.416|
        STR      r0,[r1,#0]  ; SystemCoreClock
        B        |L1.402|
|L1.356|
        LDR      r0,|L1.408|
        ADDS     r0,r0,#0x7c
        LDR      r0,[r0,#0]
        UXTB     r0,r0
        ADDS     r0,r0,#1
        LDR      r1,|L1.420|
        UDIV     r0,r1,r0
        LDR      r1,|L1.416|
        STR      r0,[r1,#0]  ; SystemCoreClock
        B        |L1.402|
|L1.378|
        LDR      r0,|L1.408|
        ADDS     r0,r0,#0x7c
        LDR      r0,[r0,#0]
        UXTB     r0,r0
        ADDS     r0,r0,#1
        MOV      r1,#0x8000
        UDIV     r0,r1,r0
        LDR      r1,|L1.416|
        STR      r0,[r1,#0]  ; SystemCoreClock
        NOP      
|L1.402|
        NOP      
|L1.404|
        POP      {r4-r10,pc}
        ENDP

|L1.408|
        DCD      0x400fc088
|L1.412|
        DCD      0x003d0900
|L1.416|
        DCD      SystemCoreClock
|L1.420|
        DCD      0x00b71b00

        AREA ||i.SystemInit||, CODE, READONLY, ALIGN=2

SystemInit PROC
        MOVS     r0,#0x20
        LDR      r1,|L2.304|
        STR      r0,[r1,#0]
        LDR      r0,|L2.308|
        LDR      r0,[r0,#0x1a0]
        AND      r0,r0,#0x20
        CBZ      r0,|L2.32|
        NOP      
|L2.20|
        LDR      r0,|L2.304|
        LDR      r0,[r0,#0]
        AND      r0,r0,#0x40
        CMP      r0,#0
        BEQ      |L2.20|
|L2.32|
        MOVS     r0,#3
        LDR      r1,|L2.304|
        SUBS     r1,r1,#0x9c
        STR      r0,[r1,#0]
        MOVS     r0,#0
        LDR      r1,|L2.308|
        STR      r0,[r1,#0x1a8]
        LDR      r1,|L2.304|
        ADDS     r1,r1,#0xc
        STR      r0,[r1,#0]
        MOVS     r0,#1
        LDR      r1,|L2.304|
        SUBS     r1,r1,#0x94
        STR      r0,[r1,#0]
        LDR      r0,|L2.312|
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0x84
        STR      r0,[r1,#0]
        MOVS     r0,#0xaa
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0x8c
        STR      r0,[r1,#0]
        MOVS     r0,#0x55
        STR      r0,[r1,#0]
        MOVS     r0,#1
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0x80
        STR      r0,[r1,#0]
        MOVS     r0,#0xaa
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0x8c
        STR      r0,[r1,#0]
        MOVS     r0,#0x55
        LDR      r1,|L2.308|
        STR      r0,[r1,#0x8c]
        NOP      
|L2.108|
        LDR      r0,|L2.308|
        ADDS     r0,r0,#0x88
        LDR      r0,[r0,#0]
        AND      r0,r0,#0x4000000
        CMP      r0,#0
        BEQ      |L2.108|
        MOVS     r0,#3
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0x80
        STR      r0,[r1,#0]
        MOVS     r0,#0xaa
        LDR      r1,|L2.308|
        STR      r0,[r1,#0x8c]
        MOVS     r0,#0x55
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0x8c
        STR      r0,[r1,#0]
        NOP      
|L2.148|
        LDR      r0,|L2.308|
        ADDS     r0,r0,#0x88
        LDR      r0,[r0,#0]
        AND      r0,r0,#0x3000000
        CMP      r0,#0x3000000
        BNE      |L2.148|
        MOVS     r0,#0x23
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0xa4
        STR      r0,[r1,#0]
        MOVS     r0,#0xaa
        LDR      r1,|L2.308|
        STR      r0,[r1,#0xac]
        MOVS     r0,#0x55
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0xac
        STR      r0,[r1,#0]
        MOVS     r0,#1
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0xa0
        STR      r0,[r1,#0]
        MOVS     r0,#0xaa
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0xac
        STR      r0,[r1,#0]
        MOVS     r0,#0x55
        LDR      r1,|L2.308|
        STR      r0,[r1,#0xac]
        NOP      
|L2.214|
        LDR      r0,|L2.308|
        ADDS     r0,r0,#0xa8
        LDR      r0,[r0,#0]
        AND      r0,r0,#0x400
        CMP      r0,#0
        BEQ      |L2.214|
        MOVS     r0,#3
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0xa0
        STR      r0,[r1,#0]
        MOVS     r0,#0xaa
        LDR      r1,|L2.308|
        STR      r0,[r1,#0xac]
        MOVS     r0,#0x55
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0xac
        STR      r0,[r1,#0]
        NOP      
|L2.254|
        LDR      r0,|L2.308|
        ADDS     r0,r0,#0xa8
        LDR      r0,[r0,#0]
        AND      r0,r0,#0x300
        CMP      r0,#0x300
        BNE      |L2.254|
        LDR      r0,|L2.316|
        LDR      r1,|L2.308|
        ADDS     r1,r1,#0xc4
        STR      r0,[r1,#0]
        MOVS     r0,#0
        LDR      r1,|L2.308|
        STR      r0,[r1,#0x1c8]
        MOV      r0,r1
        LDR      r0,[r0,#0]
        BIC      r0,r0,#0xf000
        ORR      r0,r0,#0x4000
        STR      r0,[r1,#0]
        BX       lr
        ENDP

        DCW      0x0000
|L2.304|
        DCD      0x400fc1a0
|L2.308|
        DCD      0x400fc000
|L2.312|
        DCD      0x00050063
|L2.316|
        DCD      0x042887de

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=2

SystemCoreClock
        DCD      0x05f5e100

;*** Start embedded assembler ***

#line 1 "RTE\\Device\\LPC1768\\system_LPC17xx.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___16_system_LPC17xx_c_5d646a67____REV16|
#line 463 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.4.0\\CMSIS\\Core\\Include\\cmsis_armcc.h"
|__asm___16_system_LPC17xx_c_5d646a67____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___16_system_LPC17xx_c_5d646a67____REVSH|
#line 478
|__asm___16_system_LPC17xx_c_5d646a67____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___16_system_LPC17xx_c_5d646a67____RRX|
#line 665
|__asm___16_system_LPC17xx_c_5d646a67____RRX| PROC
#line 666

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

        EXPORT SystemCoreClockUpdate [CODE]
        EXPORT SystemInit [CODE]
        EXPORT SystemCoreClock [DATA,SIZE=4]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __aeabi_uldivmod [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
